name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 22
      uses: actions/setup-node@v2
      with:
        node-version: 22.x
    - run: npm ci
    - run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 22
      uses: actions/setup-node@v2
      with:
        node-version: 22.x
    - run: npm ci
    - run: npm run lint
